project:
  type: website
  output-dir: docs

website:
  title: "Adrián **Zancajo**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

